### ISSUE TITLE
[RFC]How to test interface-github modules in runbot?

### ISSUE THREAD

**Issue by elicoidal** [OCA/interface-git#12]
Currently the OCA repo is set as demo data in interface-github modules which makes it unpractical to test given the quantity of repositories and modules:
* either it would timeout
* or it could potentially overload/crash runbot

Potential solutions:
* remove and do not replace current organization (and the tester tries with his own)
* create a demo_oca organization with demo repository and module sample (this could be used in other places or tests)
* Use an existing org/repo, known to be lightweight
* Any other option...

cc @OCA/board

**Comment by legalsylvain** [comment]
Hi @elicoidal. to test this module on Runbot, we should have access to the openerp.cfg file.  Do you know if its possible to change it. (otherwise, it would fail because credential are required)

About your solution
> remove and do not replace current organization (and the tester tries with his own)

No need to remove. Just not call sync in the test file. I think this a good and complete demo data.

> create a demo_oca organization with demo repository and module sample (this could be used in other places or tests)

It's a possibility.

regards.

**Comment by elicoidal** [comment]
@OCA/board any idea (I have no clue about cfg file) and I am personally in favor of creating a demo organization

**Comment by moylop260** [comment]
What about `mock` to simulate the response of the github?

We had a similar issue related with weblate.
Instead of create a weblate demo we just created a mock:
 - https://github.com/oca/runbot-addons/blob/11.0/runbot_travis2docker/tests/test_runbot_build.py#L40-L66

I just searched
`rgrep "mock" . --include=*.py --exclude-dir=setup`
And there are other good examples, like as Spain:
 - https://github.com/OCA/l10n-spain/blob/11.0/payment_redsys/tests/test_redsys.py#L329

**Comment by elicoidal** [comment]
@moylop260 I think mock can be a good idea too. Wouldnot it be complex to set up for such an environment as Github?

**Comment by moylop260** [comment]
Maybe, if you use a sniffer of request could get all the universe of cases.

I dont know it

But if it is too complex then let’s to use a demo org as well.

**Comment by pedrobaeza** [comment]
Closing this as answered and demo org added.
